name: image_pred
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.8
  - asttokens=3.0.0
  - attr=2.5.2
  - backcall=0.2.0
  - blas=2.137
  - blas-devel=3.9.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - cairo=1.16.0
  - certifi=2024.8.30
  - cffi=1.17.0
  - charset-normalizer=3.4.0
  - comm=0.2.2
  - contourpy=1.1.1
  - cycler=0.12.1
  - dbus=1.13.6
  - debugpy=1.8.5
  - decorator=5.1.1
  - executing=2.1.0
  - expat=2.7.1
  - fftw=3.3.10
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.53.1
  - freetype=2.14.1
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - glib=2.84.0
  - glib-tools=2.84.0
  - graphite2=1.3.14
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - gstreamer-orc=0.4.41
  - h2=4.1.0
  - harfbuzz=6.0.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=70.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib-resources=6.4.5
  - importlib_resources=6.4.5
  - intel-openmp=2022.1.0
  - ipykernel=6.29.5
  - ipython=8.12.2
  - jack=1.9.22
  - jedi=0.19.1
  - joblib=1.4.2
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - keyutils=1.6.3
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.67
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcups=2.3.3
  - libdb=6.2.32
  - libdeflate=1.17
  - libedit=3.1.20250104
  - libevent=2.1.10
  - libexpat=2.7.1
  - libffi=3.5.2
  - libflac=1.4.3
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgcrypt=1.11.1
  - libgcrypt-devel=1.11.1
  - libgcrypt-lib=1.11.1
  - libgcrypt-tools=1.11.1
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.84.0
  - libgomp=15.2.0
  - libgpg-error=1.55
  - libiconv=1.18
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm15=15.0.7
  - libltdl=2.4.3a
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnsl=2.0.1
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopus=1.5.2
  - libpng=1.6.50
  - libpq=15.3
  - libprotobuf=3.21.12
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsqlite=3.50.4
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libsystemd0=253
  - libtiff=4.5.0
  - libtool=2.5.4
  - libudev1=253
  - libuuid=2.41.2
  - libvorbis=1.3.7
  - libwebp-base=1.6.0
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - matplotlib=3.7.3
  - matplotlib-base=3.7.3
  - matplotlib-inline=0.1.7
  - mkl=2022.1.0
  - mpg123=1.32.9
  - munkres=1.1.4
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - ninja=1.13.1
  - nspr=4.37
  - nss=3.117
  - numpy=1.24.4
  - openblas=0.3.30
  - openjpeg=2.5.0
  - openssl=3.1.8
  - packaging=25.0
  - parso=0.8.4
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=24.3.1
  - pixman=0.46.4
  - platformdirs=4.3.6
  - ply=3.11
  - pooch=1.8.2
  - prompt-toolkit=3.0.48
  - prompt_toolkit=3.0.48
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=16.1
  - pulseaudio-client=16.1
  - pulseaudio-daemon=16.1
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.18.0
  - pyparsing=3.1.4
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - python=3.8.18
  - python-dateutil=2.9.0
  - python_abi=3.8
  - pytorch=1.12.1
  - pyzmq=26.2.0
  - qt-main=5.15.8
  - readline=8.2
  - requests=2.32.3
  - scikit-learn=1.3.2
  - scipy=1.10.1
  - setuptools=75.3.0
  - sip=6.7.12
  - six=1.16.0
  - sleef=3.9.0
  - stack_data=0.6.2
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.2
  - torchvision=0.13.1
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - imageio==2.35.1
      - lazy-loader==0.4
      - networkx==3.1
      - openslide-python==1.4.1
      - pandas==2.0.3
      - pytz==2025.2
      - pywavelets==1.4.1
      - scikit-image==0.21.0
      - seaborn==0.13.2
      - tifffile==2023.7.10
      - tqdm==4.67.1
      - tzdata==2025.2
prefix: /home/guruguhan/miniconda3/envs/image_pred
